version: "3"
services:
  postgres:
    image: postgres
    container_name: auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=tech-master
      - POSTGRES_PASSWORD=21536
      - POSTGRES_DB=auth
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-auth
    ports:
      - "6379:6379"